### PR TITLE
Add environment option

### PR DESCRIPTION
**Pull request by P-Seebauer**
Adds an `env` option to the function such that you can set the `NODE_ENV` to `test`

### CODE REVIEW

**Comment by P-Seebauer** [comment]
Sorry about the failing tests, they work on my machine, I'll check that with the exact versions from travis.

**Comment by kevva** [comment]
Why can't you do `NODE_ENV=test gulp`?

**Comment by P-Seebauer** [comment]
Because I have a `.watch` task that restarts the server in a different `NODE_ENV` (development) and runs the tests and lint.
Also usually some integration tests run against a real database which is annoying if the development server is also running on it.

**Comment by kevva** [comment]
Try setting them manually in your task using `process.env.NODE_ENV = 'test'` or using a plugin like https://github.com/crystalschang/gulp-env.

**Comment by sindresorhus** [comment]
This specific use-case would be better solved by https://github.com/avajs/ava/issues/1470

**Comment by P-Seebauer** [comment]
`gulp-env` (as well as `gulp-process-env`) are [both](https://github.com/rdy/gulp-process-env/blob/master/index.js#L24) [altering](https://github.com/crystalschang/gulp-env/blob/master/index.js#L130) the *global*  `process.env` and are hoping that no other running task that is accessing. These are fundamental problems of these modules and I would not see any way around that (maybe some dark Proxy-trickery would do, but it's not that simple).

`gulp-ava` is starting a new process anyway so it would not hurt to change the environment at that point.

**Pull request closed without merging**
